name: release
on:
  push:
    tags: ["v*.*.*"]
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.10"}
      - name: Install
        run: |
          python -m pip install -U pip
          pip install . pytest numpy scipy pandas matplotlib pyyaml
      - name: Smoke
        env:
          ITAC_FORCE_CPU: "1"
          ITAC_EPOCHS: "1"
          ITAC_MAX_STEPS: "2"
          ITAC_NO_TB: "1"
          ITAC_NO_PLOTS: "1"
          ITAC_SAVE: "1"
          ITAC_SKIP_EVAL: "1"
        run: python main.py --model iTAC_AD --dataset synthetic --retrain
      - name: Pack release
        env:
          TAG: ${{ github.ref_name }}
          CKPT: ${{ github.workspace }}/outputs
        run: bash scripts/make_release.sh
      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        with:
          files: release_${{ github.ref_name }}.tar.gz
